### ISSUE TITLE
You can not run suite correctly

### ISSUE THREAD

**Issue by wangrocky** [oldani/HtmlTestRunner#11]
* HtmlTestRunner version:
* Python version:
* Operating System:

### Description

suite = unittest.TestSuite()
    # suite = unittest.Suit()
    suite.addTest(KeyPageStage2("test_TradeListLoad"))

runner = HTMLTestRunner(output='test')

### What I Did

```
Generating HTML reports... 
Traceback (most recent call last):
  File "D:/03_pycharmProject/04_appiumPO/TestCase/Test_owner_SmokingTest.py", line 369, in <module>
    unittest.main(testRunner=HtmlTestRunner.HTMLTestRunner(output='example_dir'))
  File "C:\Python27\lib\unittest\main.py", line 95, in __init__
    self.runTests()
  File "C:\Python27\lib\unittest\main.py", line 232, in runTests
    self.result = testRunner.run(self.test)
  File "C:\Python27\lib\site-packages\HtmlTestRunner\runner.py", line 95, in run
    result.generate_reports(self)
  File "C:\Python27\lib\site-packages\HtmlTestRunner\result.py", line 340, in generate_reports
    tests)
  File "C:\Python27\lib\site-packages\HtmlTestRunner\result.py", line 350, in generate_file
    report_file.write(report)
TypeError: expected a string or other character buffer object
```

**Comment by oldani** [comment]
Hi @wangrocky i cannot replicate you error, could you please provide a complete example.

**Comment by oldani** [comment]
Hi @wangrocky,

Update here, I was able to replicate this error and it's already fixed, I make a bug fix release so if you upgrade to 1.1.1 you shouldn't have this issue anymore. Thanks for submitting this, if any other occur please let me know, also test with the new release and let me know if you're no longer getting this error.

**Comment by wangrocky** [comment]
thanks and I will try it, btw, nice report framework and i'm enjoying it :)

**Comment by oldani** [comment]
I'm glad to hear that:p
