### ISSUE TITLE
Getting the following error:

### ISSUE THREAD

**Issue by ItsPavan** [oldani/HtmlTestRunner#21]
* HtmlTestRunner version:0.8.3
* Python version: 3.4 and 3.6.2(anaconda distribution)
* Operating System:Windows 10

### Description
Traceback (most recent call last):
  File "C:/Users/PKumar/PycharmProjects/MentorBotWebApp/MentorBot.py", line 28, in <module>
    HTMLTestRunner.main()
  File "C:\Users\PKumar\anaconda3\lib\unittest\main.py", line 95, in __init__
    self.runTests()
  File "C:\Users\PKumar\PycharmProjects\MentorBotWebApp\HTMLTestRunner.py", line 782, in runTests
    unittest.TestProgram.runTests(self)
  File "C:\Users\PKumar\anaconda3\lib\unittest\main.py", line 256, in runTests
    self.result = testRunner.run(self.test)
  File "C:\Users\PKumar\PycharmProjects\MentorBotWebApp\HTMLTestRunner.py", line 594, in run
    result = _TestResult(self.verbosity)
  File "C:\Users\PKumar\PycharmProjects\MentorBotWebApp\HTMLTestRunner.py", line 486, in __init__
    self.outputBuffer = StringIO.StringIO()
AttributeError: type object '_io.StringIO' has no attribute 'StringIO'

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did
I was trying to import HTMLTestRunner in my appium script.
```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by oldani** [comment]
Hi @ItsPavan,

Sorry for the delay here. I will be checking this out, I have never used it with Appium and Anaconda, perhaps you could pass me over an example crashing so I can debug it.
