### ISSUE TITLE
Generating HTML reports crashed if setUpClass failed

### ISSUE THREAD

**Issue by darath2000** [oldani/HtmlTestRunner#23]
* HtmlTestRunner version:1.1.1
* Python version: 2.7.12
* Operating System: Ubuntu 16.04.2 LTS

### Description

I'm trying to run an example test class where the setUpClass raises exception.
When it comes to the generating HTML part, HtmlTestRunner crashed.

### What I Did
```
python selftest/myTest.py
Running tests... 
----------------------------------------------------------------------

======================================================================
ERROR [0.000000s]: setUpClass (__main__.Example)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "selftest/myTest.py", line 8, in setUpClass
    raise Exception("Exception in setup class")
Exception: Exception in setup class
hello world

----------------------------------------------------------------------
Ran 0 tests in 0:00:00

FAILED
 (Errors=1)

Generating HTML reports... 
Traceback (most recent call last):
  File "selftest/myTest.py", line 21, in <module>
    unittest.main(testRunner=HtmlTestRunner.HTMLTestRunner(output='example_dir'))
  File "/usr/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/usr/lib/python2.7/unittest/main.py", line 232, in runTests
    self.result = testRunner.run(self.test)
  File "/usr/local/lib/python2.7/dist-packages/HtmlTestRunner/runner.py", line 95, in run
    result.generate_reports(self)
  File "/usr/local/lib/python2.7/dist-packages/HtmlTestRunner/result.py", line 339, in generate_reports
    testRunner)
  File "/usr/local/lib/python2.7/dist-packages/HtmlTestRunner/result.py", line 316, in _report_tests
    tests = self.sort_test_list(tests)
  File "/usr/local/lib/python2.7/dist-packages/HtmlTestRunner/result.py", line 303, in sort_test_list
    return sorted(test_list, key=self.get_test_number)
  File "/usr/local/lib/python2.7/dist-packages/HtmlTestRunner/result.py", line 295, in get_test_number
    test_number = int(test_name.split('_')[1])
IndexError: list index out of range
```
Test code:
import unittest
import HtmlTestRunner

class Example(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        print "hello world"
        raise Exception("Exception in setup class")

    def test_1(self):
        self.assertTrue(1==1)
    def test_2(self):
        self.assertTrue(2==2)
    @classmethod
    def tearDownClass(cls):
        print "Tearing down class"

if __name__ == "__main__":
    unittest.main(testRunner=HtmlTestRunner.HTMLTestRunner(output='example_dir'))

**Comment by oldani** [comment]
Hi @darath2000 

Sorry for the delay here I've been kind of busy. Looks like we're not handling very well test names, i will be fixing it.
